# Generated by Django 2.2.7 on 2019-12-05 22:42

from django.db import migrations, models
import welcomepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepage', '0005_auto_20191205_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=welcomepage.models.photo_path),
        ),
    ]
